# .github/workflows/upstream-sync.yml
name: Upstream Sync           # 工作流名称，可自定义

permissions:
  contents: write             # 允许使用 GITHUB_TOKEN 推送代码

on:
  schedule:
    # 每天 04:00 (UTC+8) 运行。UTC 需减 8 小时 => 20:00 前一天
    - cron: "0 20 * * *"
  workflow_dispatch:          # 允许在 Actions 页面手动点击运行

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}   # 只在 fork 仓库里执行

    steps:
      - name: Checkout target repo            # 1) 检出你的 fork
        uses: actions/checkout@v4

      - name: Sync upstream changes           # 2) 与上游同步
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: senshinya/MoonTV    # 上游仓库
          upstream_sync_branch: main              # 上游分支
          target_sync_branch: main               # 你的分支
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync check                      # 3) 如失败则报错
        if: failure()
        run: |
          echo "[Error] 同步失败：请到 Actions 日志查看详情并手动处理冲突。" && exit 1
